"""criando os bancos de dados

Revision ID: 9913134b2fc5
Revises: 
Create Date: 2026-10-08 13:59:10.868917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9913134b2fc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alinhamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('vida_inicial', sa.Integer(), nullable=False),
    sa.Column('vida_por_nivel', sa.Integer(), nullable=False),
    sa.Column('dado_de_vida', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('deus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('magia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('escola', sa.String(length=65), nullable=True),
    sa.Column('circulo', sa.Integer(), nullable=False),
    sa.Column('tempo_de_conjuracao', sa.String(length=65), nullable=True),
    sa.Column('alcance', sa.String(length=65), nullable=True),
    sa.Column('componentes', sa.String(length=65), nullable=True),
    sa.Column('duracao', sa.String(length=65), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oficio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('ferramentas', sa.String(length=65), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('tipo_criatura', sa.String(length=65), nullable=False),
    sa.Column('tamanho', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=65), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    op.create_table('hab_classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_classe'], ['classe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hab_deus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_deus', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_deus'], ['deus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hab_raca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_raca', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_raca'], ['raca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pericia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.ForeignKeyConstraint(['id_atributo'], ['atributo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('personagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=True),
    sa.Column('id_raca', sa.Integer(), nullable=True),
    sa.Column('id_deus', sa.Integer(), nullable=True),
    sa.Column('id_oficio', sa.Integer(), nullable=True),
    sa.Column('id_alinhamento', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=True),
    sa.Column('alcunha', sa.String(length=65), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('conceito', sa.Text(), nullable=True),
    sa.Column('vida_atual', sa.Integer(), nullable=True),
    sa.Column('vida_temporaria', sa.Integer(), nullable=True),
    sa.Column('mana_atual', sa.Integer(), nullable=True),
    sa.Column('dados_vida', sa.Integer(), nullable=True),
    sa.Column('meio_conjurador', sa.Boolean(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('genero', sa.String(length=65), nullable=True),
    sa.Column('cabelo', sa.String(length=65), nullable=True),
    sa.Column('olho', sa.String(length=65), nullable=True),
    sa.Column('pele', sa.String(length=65), nullable=True),
    sa.Column('aura', sa.String(length=65), nullable=True),
    sa.Column('roupas', sa.Text(), nullable=True),
    sa.Column('basinfo_tracos_personalidade', sa.Text(), nullable=True),
    sa.Column('basinfo_ideais', sa.Text(), nullable=True),
    sa.Column('basinfo_ligacoes', sa.Text(), nullable=True),
    sa.Column('basinfo_defeitos', sa.Text(), nullable=True),
    sa.Column('dinheiro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_alinhamento'], ['alinhamento.id'], ),
    sa.ForeignKeyConstraint(['id_classe'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['id_deus'], ['deus.id'], ),
    sa.ForeignKeyConstraint(['id_oficio'], ['oficio.id'], ),
    sa.ForeignKeyConstraint(['id_raca'], ['raca.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('atual', sa.Integer(), nullable=False),
    sa.Column('maximo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defeito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ferramentas_e__habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('proeficiente', sa.Boolean(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idiomas_e__outros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('tipo_enum', sa.Enum('Idioma', 'Arma', 'Armadura', 'Outro'), nullable=True),
    sa.Column('nome', sa.String(length=65), nullable=True),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personagem__atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('proficiencia_salvaguarda', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_atributo'], ['atributo.id'], ),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personagem__magia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('id_magia', sa.Integer(), nullable=False),
    sa.Column('preparada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_magia'], ['magia.id'], ),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personagem__pericia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('id_pericia', sa.Integer(), nullable=False),
    sa.Column('proficiencia', sa.Boolean(), nullable=False),
    sa.Column('especializacao', sa.Boolean(), nullable=False),
    sa.Column('bonus_outro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pericia'], ['pericia.id'], ),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=65), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talento')
    op.drop_table('personagem__pericia')
    op.drop_table('personagem__magia')
    op.drop_table('personagem__atributo')
    op.drop_table('item')
    op.drop_table('idiomas_e__outros')
    op.drop_table('ferramentas_e__habilidades')
    op.drop_table('defeito')
    op.drop_table('contador')
    op.drop_table('personagem')
    op.drop_table('pericia')
    op.drop_table('hab_raca')
    op.drop_table('hab_deus')
    op.drop_table('hab_classe')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('raca')
    op.drop_table('oficio')
    op.drop_table('magia')
    op.drop_table('deus')
    op.drop_table('classe')
    op.drop_table('atributo')
    op.drop_table('alinhamento')
    # ### end Alembic commands ###
